### PR TITLE
Site Visual Design Update & Quel Email Notifications

### PR DESCRIPTION
**Pull request by stitzelj**
Includes restructure for main pages for Challenges and Prompts and overall global visual update

### CODE REVIEW

**Comment by stitzelj** [comment]
Honestly, I can't think of a reason for that, either, since all activity should start at zero. And I can't recall a logic issue that I might have bumped into to prompt that change.

**Comment by stitzelj** [comment]
Yup, I missed testing that one scenario. Let me work on this for a moment, and I'll add it to the PR when I'm done.

**Comment by ethel-t-frog** [comment]
Thanks, Jim.

**Comment by stitzelj** [comment]
Fix made and pushed to PR #37.

**Pull request merged**
