### PR TITLE
Email confirmation resend link; Sitemap

### PR DESCRIPTION
**Pull request by stitzelj**
Made a couple of minor modifications to the README file for clarity. Also including the the ability for unconfirmed users to request an email confirmation from their author page in this pull request.

### CODE REVIEW

**Comment by HSAR** [comment]
LGTM (shorthand, "Looks Good To Me")

**Comment by stitzelj** [comment]
Added the sitemap to this pull request. Note that you'll need to add the following line to the INSTALLED_APPS in the settings.py file in production:

`'django.contrib.sitemaps',`

**Comment by stitzelj** [comment]
I made a modification to the login process that's been bugging me for a while so that it returns the user to the page they were just looking at after logging in rather than to the front page. It involves adding a context processor to the Templates section in `settings.py` so look at the changes in `settings-examples.py` for that adjustment. (You'll also note some additional clean-up I did in that file to remove the deprecated TEMPLATE_DIRS setting in Django 1.8)

**Comment by HSAR** [comment]
LGTM

**Comment by ethel-t-frog** [comment]
Merged pull-request and it is now live on the production site.

**Pull request merged**
