### PR TITLE
Migrations cleanup, submit_story bug fix, Notes module

### PR DESCRIPTION
**Pull request by stitzelj**

### CODE REVIEW

**Comment by stitzelj** [comment]
The Notes module will require a `./manage.py makemigrations notes` then `./manage.py migrate notes` to update the database. Everything else should be ready to run straight out of the box.

**Comment by HSAR** [comment]
Am I missing the bit where a story is only hidden if it's mature?

Also, I think this Pull Request is trying to do too much. Just like commits but to a lesser extent (since PRs usually consist of a few commits anyway), PRs should generally have one well-defined purpose. I see 19 commits attached here, which is a lot.

**Comment by stitzelj** [comment]
It's under the minor fix commit. I realized after the fact that I pulled the conditional code out and shouldn't have.

I'm open to suggestions as to how to keep Pull Requests more efficient. I don't like leaving commits just on my local machine in the event  something goes wrong, but every commit I push to my repo also gets added to the current open PR.

**Comment by HSAR** [comment]
Not strictly relevant to the PR, so I'll take it offline.

**Comment by stitzelj** [comment]
Just to make this PR one commit messier, I stumbled across a couple of minor bugs (nothing that breaks anything) last night while writing a story. I've patched those for this PR.

And I promise I won't add anything else to this Pull Request. :)

**Comment by stitzelj** [comment]
I lied. I found another bug with the challenge.ended function in the Challenge model. Kinda noticed it when my challenge failed to close properly when the calendar rolled over to today.

**Comment by stitzelj** [comment]
Yeah, I switched to that method with one of my recent branches once I figured out that was the preferred method. I think all my working files now use spaces instead of tabs.

**Comment by ethel-t-frog** [comment]
Cool.

I'm really trying to get this branch merged over the next day or so.  Scouts tonight...

**Comment by stitzelj** [comment]
That'd be sweet if you can manage it. The PR I'll send you next is basically the visual update to everything on the site, so it should be easier to merge than the current PR.

**Comment by ethel-t-frog** [comment]
When the notes count is zero, could you remove the big red highlight, please?

**Comment by stitzelj** [comment]
Yup, that change makes sense. Just added the commit to the PR.

**Comment by ethel-t-frog** [comment]
Cool.

**Comment by stitzelj** [comment]
Another option would be to make the bubble a darkish grey if the count is zero, too. I'm fine with it either way.

**Comment by ethel-t-frog** [comment]
Either works for me

**Comment by ethel-t-frog** [comment]
Tweaked and merged.

**Comment by ethel-t-frog** [comment]
Oops: missed your latest push...

**Comment by stitzelj** [comment]
I don't think so. I was just bringing my master up to sync with yours.

**Comment by ethel-t-frog** [comment]
Fixed now.

**Comment by stitzelj** [comment]
Just making sure I'm not missing anything and that this PR hasn't been pushed to prod yet. I'm guessing you're to have a little time to open that particular can of worms? :)

**Comment by ethel-t-frog** [comment]
It's not in yet.  The server fun-and-games today somewhat got in the way of that.  With any luck, I'll push to the server tonight.

**Comment by stitzelj** [comment]
Kinda what I thought. I just wanted to make sure. Server was definitely up and down a bit this morning, but it seems to be stable now from what I can tell.

**Comment by ethel-t-frog** [comment]
Yeah, they had all sorts of joy involving virtual machines failing in the middle of a database update and the dodgy data being propagated to other systems and DNS going bang and all sorts.  My friend Rob was hitting it with hammers for hours this morning, but he assures me that it's back up now.

**Comment by stitzelj** [comment]
Oh, the joys of being a sysadmin.

**Comment by ethel-t-frog** [comment]
quite....

**Comment by stitzelj** [comment]
Looks like you forgot to push the updated stylesheet out to prod again. The Notes area looks way wonkier than it ought.

**Comment by ethel-t-frog** [comment]
I really need to write myself a checklist...

**Comment by ethel-t-frog** [comment]
is that better now?

**Comment by stitzelj** [comment]
lol, that's much better. Thanks s'much. :)

**Pull request merged**
